name: Build

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  # Allows to trigger this workflow by other repos
  push:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          node-path: ~\AppData\Local\npm-cache
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          architecture: x64
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm
          cache: npm
          # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
          cache-dependency-path: package-lock.json # optional
      - name: Caching node environment
        uses: pat-s/always-upload-cache@v3
        with:
          path: |
            .cache
            node_modules
            ${{ matrix.node-path }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Init App dependencies
        run: npm install
      - name: App Build (Windows)
        if: startsWith(runner.os, 'Windows')
        run: |
          npm run-script deploy-win